package summarizer

import (
	"fmt"
	"strings"
	"time"
)

// SummaryFormatter handles elegant summary formatting
type SummaryFormatter struct{}

// NewSummaryFormatter creates a new summary formatter
func NewSummaryFormatter() *SummaryFormatter {
	return &SummaryFormatter{}
}

// FormatPartialSummary formats a partial summary with elegant styling
func (sf *SummaryFormatter) FormatPartialSummary(summary string, part, total int, groupName string, startTime, endTime time.Time, messageCount int) string {
	var output strings.Builder
	
	// Header box
	output.WriteString("```\n")
	output.WriteString("╔════════════════════════════════╗\n")
	output.WriteString(fmt.Sprintf("║  📊 SUMMARY PART %d/%d          ║\n", part, total))
	output.WriteString("╚════════════════════════════════╝\n")
	output.WriteString("```\n\n")
	
	// Group info
	output.WriteString(fmt.Sprintf("*Group:* `%s`\n", groupName))
	output.WriteString(fmt.Sprintf("*Period:* `%s` - `%s`\n", 
		startTime.Format("15:04"), 
		endTime.Format("15:04")))
	output.WriteString(fmt.Sprintf("*Messages:* `~%d messages`\n\n", messageCount))
	
	// Separator
	output.WriteString("━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n")
	
	// Clean markdown from AI output first
	cleanedSummary := sf.stripMarkdown(summary)
	
	// Summary content (prettified)
	prettifiedSummary := sf.prettifySummaryContent(cleanedSummary)
	output.WriteString(prettifiedSummary)
	
	// Footer
	output.WriteString("\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")
	output.WriteString("_Generated by AI ✨_\n")
	
	return output.String()
}

// FormatCompletionMessage formats the completion message
func (sf *SummaryFormatter) FormatCompletionMessage(totalParts int) string {
	var output strings.Builder
	
	output.WriteString("```\n")
	output.WriteString("╔════════════════════════════════╗\n")
	output.WriteString("║  ✅ SUMMARIZATION COMPLETE    ║\n")
	output.WriteString("╚════════════════════════════════╝\n")
	output.WriteString("```\n\n")
	
	output.WriteString(fmt.Sprintf("📦 *Total Parts:* %d\n", totalParts))
	output.WriteString("📊 *Status:* All summaries generated\n\n")
	
	output.WriteString("_All partial summaries have been sent above._\n")
	output.WriteString("_Check monitoring bot for backup copy._\n")
	
	return output.String()
}

// stripMarkdown removes markdown formatting from text
func (sf *SummaryFormatter) stripMarkdown(text string) string {
	// Remove bold (**text** or __text__)
	text = strings.ReplaceAll(text, "**", "")
	text = strings.ReplaceAll(text, "__", "")
	
	// Remove italic/emphasis markers carefully
	// We need to preserve bullet points (-, *, •)
	lines := strings.Split(text, "\n")
	var cleaned []string
	
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		
		// Skip processing if line starts with bullet or list marker
		if strings.HasPrefix(trimmed, "- ") || 
		   strings.HasPrefix(trimmed, "* ") ||
		   strings.HasPrefix(trimmed, "• ") ||
		   len(trimmed) > 0 && (trimmed[0] >= '0' && trimmed[0] <= '9') {
			// Keep line as-is for lists
			cleaned = append(cleaned, line)
			continue
		}
		
		// For non-list lines, remove single * and _ (italic markers)
		// But be careful not to break structure
		cleanedLine := line
		// Only remove * and _ if they appear in pairs or isolated
		cleanedLine = strings.ReplaceAll(cleanedLine, "*", "")
		cleanedLine = strings.ReplaceAll(cleanedLine, "_", "")
		
		cleaned = append(cleaned, cleanedLine)
	}
	
	return strings.Join(cleaned, "\n")
}

// prettifySummaryContent enhances the summary content with better formatting
func (sf *SummaryFormatter) prettifySummaryContent(summary string) string {
	var output strings.Builder
	
	lines := strings.Split(summary, "\n")
	inCodeBlock := false
	
	for _, line := range lines {
		trimmedLine := strings.TrimSpace(line)
		
		// Skip pure separator lines and table dividers
		if trimmedLine == "---" || trimmedLine == "━━━" || trimmedLine == "═══" || 
		   strings.HasPrefix(trimmedLine, "|---") {
			continue
		}
		
		// Detect section headers (starts with ## or ###)
		if strings.HasPrefix(trimmedLine, "### ") || strings.HasPrefix(trimmedLine, "## ") {
			// Close previous code block
			if inCodeBlock {
				output.WriteString("```\n\n")
				inCodeBlock = false
			}
			
			// Extract and clean section title
			sectionTitle := strings.TrimPrefix(trimmedLine, "### ")
			sectionTitle = strings.TrimPrefix(sectionTitle, "## ")
			sectionTitle = strings.TrimSpace(sectionTitle)
			sectionTitle = sf.removeEmojiFromTitle(sectionTitle)
			
			// Get appropriate emoji
			emoji := sf.getSectionEmoji(sectionTitle)
			
			// Write section header (normal case, not UPPERCASE)
			output.WriteString(fmt.Sprintf("%s *%s*\n", emoji, sectionTitle))
			output.WriteString("```\n")
			inCodeBlock = true
			continue
		}
		
		// Skip sub-headers (####) - they're usually unnecessary
		if strings.HasPrefix(trimmedLine, "#### ") {
			continue
		}
		
		// Regular content - just pass through
		if trimmedLine != "" {
			if !inCodeBlock {
				output.WriteString("```\n")
				inCodeBlock = true
			}
			output.WriteString(line + "\n")
		} else {
			// Empty line - keep it for readability
			if inCodeBlock {
				output.WriteString("\n")
			}
		}
	}
	
	// Close final code block
	if inCodeBlock {
		output.WriteString("```")
	}
	
	return output.String()
}

// removeEmojiFromTitle removes emoji from beginning of title
func (sf *SummaryFormatter) removeEmojiFromTitle(title string) string {
	// Common emojis that might be in AI output
	emojis := []string{"📅", "🔥", "📦", "✅", "🚩", "💡", "🎯", "💬", "💰", "📌", "📊"}
	
	for _, emoji := range emojis {
		if strings.HasPrefix(title, emoji) {
			title = strings.TrimPrefix(title, emoji)
			title = strings.TrimSpace(title)
			break
		}
	}
	
	return title
}

// getSectionEmoji returns appropriate emoji for section titles
func (sf *SummaryFormatter) getSectionEmoji(title string) string {
	titleLower := strings.ToLower(title)
	
	if strings.Contains(titleLower, "ringkasan") || strings.Contains(titleLower, "summary") {
		return "📅"
	}
	if strings.Contains(titleLower, "topik") || strings.Contains(titleLower, "topic") {
		return "🔥"
	}
	if strings.Contains(titleLower, "produk") || strings.Contains(titleLower, "product") {
		return "📦"
	}
	if strings.Contains(titleLower, "validasi") || strings.Contains(titleLower, "validation") {
		return "✅"
	}
	if strings.Contains(titleLower, "red flag") || strings.Contains(titleLower, "warning") {
		return "🚩"
	}
	if strings.Contains(titleLower, "kesimpulan") || strings.Contains(titleLower, "conclusion") {
		return "💡"
	}
	if strings.Contains(titleLower, "insight") || strings.Contains(titleLower, "analysis") {
		return "🎯"
	}
	if strings.Contains(titleLower, "testimoni") || strings.Contains(titleLower, "testimon") {
		return "💬"
	}
	if strings.Contains(titleLower, "harga") || strings.Contains(titleLower, "price") {
		return "💰"
	}
	
	// Default emoji
	return "📌"
}
